[program:weatherradar]
command = /opt/weatherradar/venv/scripts/start_gunicorn.sh
autostart = true
autorestart = true
user = weatherradar

stdout_logfile = /opt/weatherradar/logs/gunicorn.log
redirect_stderr = true